version: '1.0.{build}'
image:
   - Visual Studio 2017
   - Ubuntu
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - dotnet --version
  # Display minimal restore text
  - dotnet restore FirebaseAdmin/FirebaseAdmin.sln --verbosity m
build_script:
  - dotnet build FirebaseAdmin
after_build:
  # For once the build has completed
clone_depth: 1
test_script:
  - dotnet test FirebaseAdmin/FirebaseAdmin.Tests
on_finish :
  # any cleanup in here
deploy: off